### ISSUE TITLE
Playchess-Games-Machines

### ISSUE THREAD

**Issue by DominoA4** [fsmosca/Python-Chess-Scripts#12]
Is it possible to process "PGN File" from "PlayChess Games"?  Tell me how to make please. Scripts - evalswing.

**Comment by fsmosca** [comment]
Could you post a sample game from playchess pgn file?

**Comment by DominoA4** [comment]
> Не могли бы вы выложить образец игры из файла playchess pgn?

[Event "Monday 19 April Blitz, 5+0, 19 ROUNDS"]
[Site "Machines A"]
[Date "2021.04.19"]
[Round "1"]
[White "Mymoso, Fat Fritz 2"]
[Black "Taras0404, Stockfish 13"]
[Result "1/2-1/2"]
[WhiteElo "2727"]
[BlackElo "2743"]
[PlyCount "109"]
[EventDate "2021.04.19"]
[EventType "swiss (blitz)"]

1. e4 {[%eval 0,0] [%emt 0:00:00]} e5 {[%eval 0,0] [%emt 0:00:00]} 2. Nf3 {
[%eval 0,0] [%emt 0:00:00]} Nc6 {[%eval 0,0] [%emt 0:00:00]} 3. Bb5 {[%eval 0,
0] [%emt 0:00:00]} Nf6 {[%eval 0,0] [%emt 0:00:00]} 4. O-O {[%eval 0,0] [%emt
0:00:00]} Nxe4 {[%eval 0,0] [%emt 0:00:00]} 5. d4 {[%eval 0,0] [%emt 0:00:00]}
Nd6 {[%eval 0,0] [%emt 0:00:00]} 6. Bxc6 {[%eval 0,0] [%emt 0:00:00]} dxc6 {
[%eval 0,0] [%emt 0:00:00]} 7. dxe5 {[%eval 0,0] [%emt 0:00:00]} Nf5 {[%eval 0,
0] [%emt 0:00:00]} 8. Qxd8+ {[%eval 0,0] [%emt 0:00:00]} Kxd8 {[%eval 0,0] 
[%emt 0:00:00]} 9. h3 {[%eval 0,0] [%emt 0:00:00]} Be7 {[%eval 0,0] [%emt 0:00:
00]} 10. Rd1+ {[%eval 0,0] [%emt 0:00:00]} Ke8 {[%eval 0,0] [%emt 0:00:00]} 11.
Nc3 {[%eval 0,0] [%emt 0:00:00]} Nh4 {[%eval 0,0] [%emt 0:00:00]} 12. Nxh4 {
[%eval 0,0] [%emt 0:00:00]} Bxh4 {[%eval 0,0] [%emt 0:00:00]} 13. g4 {[%eval 0,
0] [%emt 0:00:00]} h5 {[%eval 0,0] [%emt 0:00:00]} 14. f3 {[%eval 0,0] [%emt 0:
00:00]} f6 {[%eval 0,0] [%emt 0:00:00]} 15. exf6 {[%eval 8,38] [%emt 0:00:09]}
gxf6 {[%eval 0,0] [%emt 0:00:00]} 16. Bf4 {[%eval 0,0] [%emt 0:00:00]} Be6 {
[%eval 0,0] [%emt 0:00:00]} 17. Ne2 {[%eval 0,0] [%emt 0:00:00]} Kf7 {[%eval 0,
0] [%emt 0:00:00]} 18. Nd4 {[%eval 0,0] [%emt 0:00:00]} Rae8 {[%eval 0,0] 
[%emt 0:00:00]} 19. Nxe6 {[%eval 0,0] [%emt 0:00:00]} Rxe6 {[%eval 0,0] [%emt
0:00:00]} 20. Rd7+ {[%eval 0,0] [%emt 0:00:00]} Kg6 {[%eval 0,0] [%emt 0:00:00]
} 21. Rad1 {[%eval 0,0] [%emt 0:00:00]} Rhe8 {[%eval 0,0] [%emt 0:00:00]} 22.
gxh5+ {[%eval 0,0] [%emt 0:00:00]} Kf5 {[%eval 0,0] [%emt 0:00:00]} 23. Bh2 {
[%eval 0,0] [%emt 0:00:00]} Re1+ {[%eval 0,0] [%emt 0:00:00]} 24. Rxe1 {
[%eval 0,50] [%emt 0:00:05]} Rxe1+ {[%eval 0,0] [%emt 0:00:00]} 25. Kg2 {
[%eval 0,47] [%emt 0:00:04]} Re2+ {[%eval 0,0] [%emt 0:00:00]} 26. Kh1 {
[%eval 0,47] [%emt 0:00:05]} Kg5 {[%eval 0,0] [%emt 0:00:00]} 27. Bxc7 {
[%eval 0,47] [%emt 0:00:06]} Re1+ {[%eval 0,58] [%emt 0:00:10]} 28. Kg2 {
[%eval 0,55] [%emt 0:00:09]} Re2+ {[%eval 0,0] [%emt 0:00:00]} 29. Kf1 {
[%eval 0,52] [%emt 0:00:04]} Re1+ {[%eval 0,55] [%emt 0:00:05]} 30. Kg2 {
[%eval 0,54] [%emt 0:00:00]} Re2+ {[%eval 0,59] [%emt 0:00:07]} 31. Kh1 {
[%eval 0,59] [%emt 0:00:15]} Re1+ {[%eval 0,63] [%emt 0:00:00]} 32. Kh2 {
[%eval 0,62] [%emt 0:00:11]} Re2+ {[%eval 0,63] [%emt 0:00:00]} 33. Kg1 {
[%eval 0,61] [%emt 0:00:18] (Kh1)} Rxc2 {[%eval 0,65] [%emt 0:00:09]} 34. f4+ {
[%eval 0,60] [%emt 0:00:00]} Kh6 {[%eval 0,69] [%emt 0:00:07]} 35. Bd6 {
[%eval 0,60] [%emt 0:00:00]} Bf2+ {[%eval 0,69] [%emt 0:00:11]} 36. Kg2 {
[%eval 0,61] [%emt 0:00:00]} Bc5+ {[%eval 0,70] [%emt 0:00:05]} 37. Kf3 {
[%eval 0,44] [%emt 0:00:05]} Bxd6 {[%eval 0,70] [%emt 0:00:00]} 38. Rxd6 {
[%eval 0,57] [%emt 0:00:05]} Kxh5 {[%eval 0,65] [%emt 0:00:04]} 39. Rxf6 {
[%eval 0,58] [%emt 0:00:00]} Rxb2 {[%eval 0,73] [%emt 0:00:07]} 40. a4 {
[%eval 0,63] [%emt 0:00:00]} Rb3+ {[%eval 0,71] [%emt 0:00:05]} 41. Ke4 {
[%eval 0,70] [%emt 0:00:04]} a5 {[%eval 0,74] [%emt 0:00:00]} 42. Rf5+ {
[%eval 0,90] [%emt 0:00:05]} Kg6 {[%eval 0,81] [%emt 0:00:01]} 43. Rxa5 {
[%eval 0,74] [%emt 0:00:05]} b5 {[%eval 0,89] [%emt 0:00:00]} 44. h4 {[%eval 0,
78] [%emt 0:00:04] (axb5)} bxa4 {[%eval 0,87] [%emt 0:00:07]} 45. f5+ {[%eval
0,245] [%emt 0:00:06] (Rxa4)} Kf6 {[%eval 0,98] [%emt 0:00:10]} 46. Rxa4 {
[%eval 0,141] [%emt 0:00:01] (Ra6)} Rh3 {[%eval 0,126] [%emt 0:00:08]} 47. Rc4
{[%eval 0,52] [%emt 0:00:04] (Ra8)} c5 {[%eval 0,136] [%emt 0:00:09]} 48. Rxc5
{[%eval 0,52] [%emt 0:00:03] (Kd5)} Rxh4+ {[%eval -28000,0] [%emt 0:00:00]} 49.
Ke3 {[%eval -28000,0] [%emt 0:00:00]} Rb4 {[%eval -28000,0] [%emt 0:00:00]} 50.
Rd5 {[%eval -28000,0] [%emt 0:00:00]} Ra4 {[%eval -28000,0] [%emt 0:00:00]} 51.
Rc5 {[%eval -28000,0] [%emt 0:00:00]} Ra3+ {[%eval -28000,0] [%emt 0:00:00]}
52. Kd4 {[%eval -28000,0] [%emt 0:00:00]} Ra4+ {[%eval -28000,0] [%emt 0:00:00]
} 53. Ke3 {[%eval -28000,0] [%emt 0:00:00]} Ra3+ {[%eval -28000,0] [%emt 0:00:
00]} 54. Kd4 {[%eval -28000,0] [%emt 0:00:00]} Ra4+ {[%eval -28000,0] [%emt 0:
00:00]} 55. Ke3 {[%eval -28000,0] [%emt 0:00:00]} 1/2-1/2

**Comment by DominoA4** [comment]
pgn file: https://pixeldrain.com/u/z3xzAUy7

**Comment by fsmosca** [comment]
evalswing is updated use version 0.3.1.

This is the change https://github.com/fsmosca/Python-Chess-Scripts/commit/938af4375dbbe22c3bef7ad905274d0e92fcce99

### Example command line
`python eval_swing.py --input sample.pgn --chessbase`

### Output
Output from the given pgn.

```
 #                White                    Black      Res  WMaxMove  WMaxEval  WMinMove  WMinEval  BMaxMove  BMaxEval  BMinMove  BMinEval
 1  Mymoso, Fat Fritz 2  Taras0404, Stockfish 13  1/2-1/2        15      0.08        49    -280.0        48     280.0         1       0.0
```

**Comment by DominoA4** [comment]
Thank you! A very useful program.
