### ISSUE TITLE
Create images in a separate folder in the pgn dir (Enhancement)

### ISSUE THREAD

**Issue by rwbc** [fsmosca/Python-Chess-Scripts#4]
A suggestion for a tiny enhancement for later:
Create the images in a folder named after the pgn file.

Guenther

**Comment by fsmosca** [comment]
Currently if pgn file` mygame.pgn` is in the `pgn` folder, command line would be:

`... --input ./pgn/mygame.pgn ...`

And images will be saved in the `pgn` folder.

If that is not enough I will implement it but will put a flag `--create-folder` to enable such feature.

**Comment by rwbc** [comment]
> 
> 
> Currently if pgn file` mygame.pgn` is in the `pgn` folder, command line would be:
> 
> `... --input ./pgn/mygame.pgn ...`
> 
> And images will be saved in the `pgn` folder.
> 
> If that is not enough I will implement it but will put a flag `--create-folder` to enable such feature.

I think that is enough already. You might close this issue.
